# Config version for compatibility and deprecations
config-version = 2

# Commands that run after AeroSpace startup
after-startup-command = ['exec-and-forget sketchybar --trigger aerospace_workspace_change']

# Start AeroSpace at login
start-at-login = true

# Normalizations
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Accordion padding
accordion-padding = 30

# Default layout
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Unhide macOS hidden apps
automatically-unhide-macos-hidden-apps = false

# Persistent workspaces
persistent-workspaces = ["1", "2", "3", "4", "5", "6"]

# exec-on-workspace-change = ['/bin/bash', '-c',
#     'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
# ]
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

on-mode-changed = []

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

[mode.main.binding]
    # Layout
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # Focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # Move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Navigate workspaces
    # alt-right = 'workspace next'
    # alt-left = 'workspace prev'
    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # Workspace switching
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'

    # Move node to workspace
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'

    # Modes
    alt-a = ['exec-and-forget open -n -b com.mitchellh.ghostty']
    alt-v = ['exec-and-forget open -n -b com.asiafu.Bloom']
    alt-t = 'layout floating tiling'
    # alt-shift-semicolon = 'mode service'
    alt-shift-semicolon = ['mode service', 'exec-and-forget sketchybar --trigger aerospace_mode_changed MODE=service']

    alt-shift-f = 'fullscreen'

    # Close window
    alt-shift-backspace = 'close'

[mode.service.binding]
    esc = ['reload-config', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed MODE=main']
    alt-r = ['flatten-workspace-tree', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed MODE=main']
    alt-t = ['layout floating tiling', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed MODE=main']
    alt-shift-backspace = ['close-all-windows-but-current', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed MODE=main']

    alt-h = ['join-with left', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed MODE=main']
    alt-j = ['join-with down', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed MODE=main']
    alt-k = ['join-with up', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed MODE=main']
    alt-l = ['join-with right', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed MODE=main']

    # esc = ['reload-config', 'mode main']

    # r = ['flatten-workspace-tree', 'mode main']
    # f = ['layout floating tiling', 'mode main']
    # backspace = ['close-all-windows-but-current', 'mode main']

    # alt-shift-h = ['join-with left', 'mode main']
    # alt-shift-j = ['join-with down', 'mode main']
    # alt-shift-k = ['join-with up', 'mode main']
    # alt-shift-l = ['join-with right', 'mode main']

# [[on-window-detected]]
#     if.app-id = 'com.mitchellh.ghostty'
#     run = ['move-node-to-workspace 1', 'layout accordion']

# [[on-window-detected]]
#     if.app-id = 'com.adobe.Photoshop'
#     run = 'move-node-to-workspace 2'

[[on-window-detected]]
    if.app-id = 'com.blackmagic-design.DaVinciResolve'
    if.window-title-regex-substring = '^$'
    run = 'move-node-to-workspace 6'

[[on-window-detected]]
    if.app-id = 'com.blackmagic-design.DaVinciResolve'
    run = 'move-node-to-workspace 3'

[[on-window-detected]]
    if.app-id = 'com.apple.Safari'
    run = 'move-node-to-workspace 4'

[[on-window-detected]]
    if.app-id = 'org.mozilla.firefox'
    run = 'move-node-to-workspace 4'

[[on-window-detected]]
    if.app-id = 'net.freemacsoft.AppCleaner'
    run = 'layout floating tiling'

[workspace-to-monitor-force-assignment]
    "1" = 'main'
    "2" = 'main'
    "3" = 'main'
    "4" = 'secondary'
    "5" = 'secondary'
    "6" = 'secondary'
